python train.py --name APNet \
    --hdf5FolderPath YOUR_FAIR_PLAY_SPLIT_PATH \
    --save_epoch_freq 50 \
    --display_freq 10 \
    --save_latest_freq 100 \
    --batchSize 256 \
    --learning_rate_decrease_itr 10 \
    --niter 1000 \
    --lr_visual 0.0001 \
    --lr_audio 0.001 \
    --nThreads 32 \
    --gpu_ids 0,1,2,3 \
    --validation_on \
    --validation_freq 100 \
    --validation_batches 50 \
    --fusion_model APNet \
    --val_return_key stereo_loss_fusion \
    --tensorboard True |& tee -a logs/APNet.log
