python train.py --name AudioNet_sep \
    --MUSICPath ./data/dummy_MUSIC_split \
    --dataset_mode sep \
    --save_epoch_freq 10 \
    --display_freq 10 \
    --save_latest_freq 100 \
    --batchSize 256 \
    --learning_rate_decrease_itr 2 \
    --niter 200 \
    --lr_visual 0.0001 \
    --lr_audio 0.001 \
    --nThreads 32 \
    --gpu_ids 0,1,2,3 \
    --validation_on \
    --validation_freq 100 \
    --validation_batches 50 \
    --loss_mode l1 \
    --val_return_key sep_loss \
    --tensorboard True |& tee -a logs/AudioNet_sep.log
